version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: password
      TZ: "Europe/Kiev"
    ports:
      - "5432"
    volumes:
      - db_postgres:/var/lib/postgresql/data
  web:
    tty: true
    stdin_open: true
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.local
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/print-crm
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      TZ: "Europe/Kiev"
volumes:
  db_postgres:
